CREATE TABLE EMPLEADO (
       ID INTEGER PRIMARY KEY,
       RAZON_SOCIAL VARCHAR(20),
       DNI_CUIL VARCHAR(20),
       FECHA_ALTA DATE
);

CREATE TABLE FACTURA(
       ID INTEGER PRIMARY KEY,
       NOMBRE VARCHAR(20),
       NUM_FACTURA VARCHAR(20),
       ID_CLIENTE INTEGER ,
       FOREIGN KEY (ID_CLIENTE) REFERENCES EMPLEADO(ID)
       );
CREATE TABLE FACTURA_PRODUCTO(
ID_FACTURA INTEGER ,
ID_PRODUCTO INTEGER ,
PRIMARY KEY (ID_FACTURA,ID_PRODUCTO),
CANTIDAD VARCHAR(20),
FOREIGN KEY (id_FACTURA) REFERENCES FACTURA(id),
FOREIGN KEY (id_PRODUCTO) REFERENCES PRODUCTO(ID)
);
CREATE TABLE PRODUCTO(
ID INTEGER PRIMARY KEY,
PRECIO_UNIT INTEGER,
STOCK_ACTUAL INTEGER
);
      
